on:
  push:
    branches:
      - master 





jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 'printing folder content(before)'
        run: ls

      - uses: actions/checkout@v3

      - name: 'doker login'
        run: docker login --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}}

      - name: 'building docker image'
        run: docker build -t ${{secrets.USERNAME}}/myimg .

      - name: 'pushing to docker hub'
        run: docker push  ${{secrets.USERNAME}}/myimg 


